[package]
name = "lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bunt = "0.2.8"
clap = { version = "4.4.11", features = ["derive"] }
color-eyre = "0.6.2"
logos = "0.13.0"
self_cell = "1.0.3"
